basePath: /
definitions:
  big.Float:
    type: object
  big.Int:
    type: object
  ecdsa.PrivateKey:
    properties:
      d:
        $ref: '#/definitions/big.Int'
      elliptic.Curve: {}
      x:
        $ref: '#/definitions/big.Int'
    type: object
  ecdsa.PublicKey:
    properties:
      elliptic.Curve: {}
      x:
        $ref: '#/definitions/big.Int'
    type: object
  network.DeleteNetworkRequest:
    properties:
      name:
        type: string
    type: object
  network.DescribeNetworkResponse:
    properties:
      api:
        properties:
          graphQLConfig:
            properties:
              hosts:
                items:
                  type: string
                type: array
            type: object
          grpcConfig:
            properties:
              hosts:
                items:
                  type: string
                type: array
              retries:
                type: integer
            type: object
          restConfig:
            properties:
              hosts:
                items:
                  type: string
                type: array
            type: object
        type: object
      console:
        properties:
          localPort:
            type: integer
          url:
            type: string
        type: object
      host:
        type: string
      logLevel:
        type: string
      name:
        type: string
      port:
        type: integer
      tokenExpiry:
        type: string
    type: object
  network.ImportNetworkFromSourceRequest:
    properties:
      filePath:
        type: string
      force:
        type: boolean
      name:
        type: string
      url:
        type: string
    type: object
  network.ImportNetworkFromSourceResponse:
    properties:
      filePath:
        type: string
      name:
        type: string
    type: object
  network.ListNetworksResponse:
    properties:
      networks:
        items:
          type: string
        type: array
    type: object
  types.Transaction:
    type: object
  wallet.CreateTransactionRequest:
    properties:
      amount:
        type: integer
      toAddressHex:
        type: string
    type: object
  wallet.CreateWalletRequest:
    properties:
      passphrase:
        type: string
    type: object
  wallet.CreateWalletResponse:
    properties:
      address:
        type: string
      privateKey:
        $ref: '#/definitions/ecdsa.PrivateKey'
      publicKey:
        $ref: '#/definitions/ecdsa.PublicKey'
    type: object
  wallet.DeleteWalletRequest:
    properties:
      wallet:
        type: string
    type: object
  wallet.GetWalletInfoResponse:
    properties:
      address:
        type: string
      balance:
        $ref: '#/definitions/big.Float'
    type: object
  wallet.ImportWalletRequest:
    properties:
      newPassphrase:
        type: string
      passphrase:
        description: File          os.File
        type: string
      privateKey:
        type: string
    type: object
  wallet.ImportWalletResponse:
    properties:
      address:
        type: string
    type: object
  wallet.SendTransactionRequest:
    properties:
      privateKey:
        type: string
      transactionHex:
        type: string
    type: object
  wallet.SignTransactionRequest:
    properties:
      privateKey:
        type: string
      transactionHex:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: info@info.info
    name: API Support
  description: This is a crypto wallet api
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Crypto Wallet API
  version: "1.0"
paths:
  /hello:
    get:
      consumes:
      - application/json
      description: Method to say hello
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Method to say hello
      tags:
      - hello
  /networks:
    delete:
      consumes:
      - application/json
      description: Method for Delete network
      parameters:
      - description: The input for delete network
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/network.DeleteNetworkRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete network info
      tags:
      - networks
  /networks/:
    get:
      consumes:
      - application/json
      description: Method for get networks
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/network.ListNetworksResponse'
      summary: Get networks
      tags:
      - networks
  /networks/{name}:
    get:
      consumes:
      - application/json
      description: Method for get network info
      parameters:
      - description: Network name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/network.DescribeNetworkResponse'
      summary: Get network info
      tags:
      - networks
  /networks/import:
    post:
      consumes:
      - application/json
      description: Method for import network
      parameters:
      - description: The input for import network
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/network.ImportNetworkFromSourceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/network.ImportNetworkFromSourceResponse'
      summary: Import network info
      tags:
      - networks
  /transactions/{blockNumber}:
    get:
      consumes:
      - application/json
      description: Method for get transactions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: int
      summary: Get transactions
      tags:
      - transactions
  /transactions/create:
    post:
      consumes:
      - application/json
      description: Method for create transaction
      parameters:
      - description: The input for create transaction
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/wallet.CreateTransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Transaction'
      summary: Create Transaction
      tags:
      - transactions
  /transactions/send:
    post:
      consumes:
      - application/json
      description: Method for send transaction
      parameters:
      - description: The input for send transaction
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/wallet.SendTransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Transaction'
      summary: Send Transaction
      tags:
      - transactions
  /transactions/sign:
    post:
      consumes:
      - application/json
      description: Method for sign transaction
      parameters:
      - description: The input for sign transaction
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/wallet.SignTransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Transaction'
      summary: Sign Transaction
      tags:
      - transactions
  /wallets:
    delete:
      consumes:
      - application/json
      description: Method for Delete wallet
      parameters:
      - description: The input for delete wallet
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/wallet.DeleteWalletRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Delete wallet info
      tags:
      - wallets
    post:
      consumes:
      - application/json
      description: Method for create wallet
      parameters:
      - description: The input for create wallet
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/wallet.CreateWalletRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/wallet.CreateWalletResponse'
      summary: Create wallet info
      tags:
      - wallets
  /wallets/{address}:
    get:
      consumes:
      - application/json
      description: Method for get wallet info
      parameters:
      - description: Wallet Address
        in: path
        name: address
        required: true
        type: string
      - description: Pass phrase
        in: query
        name: passphrase
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/wallet.GetWalletInfoResponse'
      summary: Get wallet info
      tags:
      - wallets
  /wallets/import:
    post:
      consumes:
      - application/json
      description: Method for import wallet
      parameters:
      - description: The input for import wallet
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/wallet.ImportWalletRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/wallet.ImportWalletResponse'
      summary: Import wallet info
      tags:
      - wallets
swagger: "2.0"
